import SwiftUI

/// The Explain sheet: an interlinear gloss of the current line, generated by
/// the LLM and cached on the cue (port of the desktop ExplainPanel). Opening
/// the sheet is the explicit "explain this line" action; a cached gloss shows
/// instantly with no new call.
struct ExplainSheet: View {
    let cue: Cue
    let onGenerated: (SentenceGloss) -> Void

    @ObservedObject private var settings = AppSettings.shared
    @State private var gloss: SentenceGloss?
    @State private var loading = false
    @State private var errorMessage: String?

    init(cue: Cue, onGenerated: @escaping (SentenceGloss) -> Void) {
        self.cue = cue
        self.onGenerated = onGenerated
        _gloss = State(initialValue: cue.gloss)
    }

    var body: some View {
        NavigationStack {
            Group {
                if let gloss {
                    glossView(gloss)
                } else if loading {
                    VStack(spacing: 10) {
                        ProgressView()
                        Text("Explaining…").font(.subheadline).foregroundStyle(.secondary)
                    }
                } else if let errorMessage {
                    ContentUnavailableView {
                        Label("Couldn't explain", systemImage: "exclamationmark.bubble")
                    } description: {
                        Text(errorMessage)
                    } actions: {
                        Button("Retry") { generate() }
                    }
                }
            }
            .navigationTitle("Explain")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .primaryAction) {
                    Button {
                        generate()
                    } label: {
                        Image(systemName: "arrow.clockwise")
                    }
                    .disabled(loading)
                }
            }
            .task {
                if gloss == nil { generate() }
            }
        }
        .presentationDetents([.medium, .large])
        .presentationDragIndicator(.visible)
    }

    private func generate() {
        guard !loading else { return }
        guard settings.isConfigured else {
            errorMessage = "Set your OpenRouter key in Settings first."
            return
        }
        loading = true
        errorMessage = nil
        Task {
            do {
                let result = try await OpenRouterService.glossSentence(
                    cue.text,
                    opts: .init(apiKey: settings.openrouterKey.trimmed, model: settings.model))
                gloss = result
                onGenerated(result)
            } catch {
                errorMessage = (error as? LocalizedError)?.errorDescription ?? String(describing: error)
            }
            loading = false
        }
    }

    private func glossView(_ gloss: SentenceGloss) -> some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 18) {
                ForEach(Array(gloss.chunks.enumerated()), id: \.offset) { _, chunk in
                    VStack(alignment: .leading, spacing: 6) {
                        HStack(alignment: .firstTextBaseline, spacing: 8) {
                            Text(chunk.phrase).font(.headline)
                            if !chunk.reading.isEmpty {
                                Text(chunk.reading).font(.caption).foregroundStyle(.secondary)
                            }
                        }
                        VStack(alignment: .leading, spacing: 3) {
                            ForEach(Array(chunk.items.enumerated()), id: \.offset) { _, item in
                                HStack(alignment: .firstTextBaseline, spacing: 6) {
                                    Text(item.token).font(.subheadline.weight(.semibold))
                                    if !item.reading.isEmpty {
                                        Text("(\(item.reading))")
                                            .font(.caption)
                                            .foregroundStyle(.secondary)
                                    }
                                    Text(item.gloss).font(.subheadline)
                                }
                            }
                        }
                        .padding(.leading, 10)
                        .overlay(alignment: .leading) {
                            Rectangle().fill(.quaternary).frame(width: 2)
                        }
                        if !chunk.translation.isEmpty {
                            Text("→ \(chunk.translation)")
                                .font(.footnote)
                                .italic()
                                .foregroundStyle(.secondary)
                        }
                    }
                }

                if !gloss.naturalTranslation.isEmpty {
                    Divider()
                    Text(gloss.naturalTranslation).font(.callout.weight(.medium))
                }
                if !gloss.intent.isEmpty {
                    Text(gloss.intent)
                        .font(.footnote)
                        .italic()
                        .foregroundStyle(.secondary)
                }
            }
            .padding()
            .frame(maxWidth: .infinity, alignment: .leading)
        }
    }
}
