import Foundation

/// Fetches YouTube caption tracks, replacing the desktop's
/// `yt-dlp --write-subs` path (ytdlp.ts probeWithSubs / downloadSubtitles).
///
/// Anonymous requests to the classic timedtext URLs from the watch page now
/// return empty bodies (proof-of-origin gating), but the InnerTube player API
/// with a current mobile client context still hands out working URLs — the
/// same client family YouTubeKit uses for streams. The client version below
/// may need bumping when YouTube retires it.
enum CaptionsService {
    struct Track {
        var languageCode: String
        /// True for YouTube's auto-generated (asr) captions.
        var isAutoGenerated: Bool
        var baseURL: URL
    }

    enum CaptionsError: Error, LocalizedError {
        case api(Int)
        case emptyTrack

        var errorDescription: String? {
            switch self {
            case .api(let status): return "captions lookup failed (HTTP \(status))"
            case .emptyTrack: return "YouTube returned an empty subtitle track."
            }
        }
    }

    // Mirror of YouTubeKit's current IOS InnerTube client.
    private static let clientVersion = "20.10.4"
    private static let userAgent =
        "com.google.ios.youtube/\(clientVersion) (iPhone16,2; U; CPU iOS 18_3_2 like Mac OS X;)"

    /// List the video's caption tracks via the InnerTube player endpoint.
    static func listTracks(videoID: String) async throws -> [Track] {
        var request = URLRequest(url: URL(string: "https://www.youtube.com/youtubei/v1/player")!)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue(userAgent, forHTTPHeaderField: "User-Agent")
        request.setValue("5", forHTTPHeaderField: "X-Youtube-Client-Name")
        request.setValue(clientVersion, forHTTPHeaderField: "X-Youtube-Client-Version")
        request.httpBody = try JSONSerialization.data(withJSONObject: [
            "context": [
                "client": [
                    "clientName": "IOS",
                    "clientVersion": clientVersion,
                    "deviceModel": "iPhone16,2",
                    "hl": "ja",
                ],
            ],
            "videoId": videoID,
        ])

        let (data, response) = try await URLSession.shared.data(for: request)
        let status = (response as? HTTPURLResponse)?.statusCode ?? 0
        guard status == 200 else { throw CaptionsError.api(status) }

        struct PlayerResponse: Decodable {
            struct Captions: Decodable {
                struct Renderer: Decodable {
                    struct CaptionTrack: Decodable {
                        var baseUrl: String
                        var languageCode: String
                        var kind: String?
                    }
                    var captionTracks: [CaptionTrack]?
                }
                var playerCaptionsTracklistRenderer: Renderer?
            }
            var captions: Captions?
        }

        let parsed = try JSONDecoder().decode(PlayerResponse.self, from: data)
        let tracks = parsed.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? []
        return tracks.compactMap { t in
            guard let url = URL(string: t.baseUrl) else { return nil }
            return Track(languageCode: t.languageCode, isAutoGenerated: t.kind == "asr", baseURL: url)
        }
    }

    /// The uploader's own Japanese subtitles, if any (auto-captions excluded —
    /// same rule as the desktop probe).
    static func manualJapanese(in tracks: [Track]) -> Track? {
        tracks.first { $0.languageCode.hasPrefix("ja") && !$0.isAutoGenerated }
    }

    /// Download a track as json3 and convert its events into cues.
    static func fetchCues(track: Track) async throws -> [Cue] {
        var components = URLComponents(url: track.baseURL, resolvingAgainstBaseURL: false)!
        components.queryItems = (components.queryItems ?? []) + [URLQueryItem(name: "fmt", value: "json3")]

        var request = URLRequest(url: components.url!)
        request.setValue(userAgent, forHTTPHeaderField: "User-Agent")
        let (data, response) = try await URLSession.shared.data(for: request)
        let status = (response as? HTTPURLResponse)?.statusCode ?? 0
        guard status == 200, !data.isEmpty else { throw CaptionsError.emptyTrack }

        struct Json3: Decodable {
            struct Event: Decodable {
                struct Seg: Decodable { var utf8: String? }
                var tStartMs: Int?
                var dDurationMs: Int?
                var segs: [Seg]?
            }
            var events: [Event]?
        }

        let parsed = try JSONDecoder().decode(Json3.self, from: data)
        var cues: [Cue] = []
        var idx = 0
        for event in parsed.events ?? [] {
            guard let segs = event.segs, let start = event.tStartMs else { continue }
            let text = segs.compactMap(\.utf8).joined()
                .replacingOccurrences(of: "\n", with: " ")
                .replacingOccurrences(of: "\\s+", with: " ", options: .regularExpression)
                .trimmingCharacters(in: .whitespacesAndNewlines)
            guard !text.isEmpty else { continue }
            let end = start + max(event.dDurationMs ?? 0, 1)
            cues.append(Cue(index: idx, startMs: start, endMs: end, text: text))
            idx += 1
        }
        guard !cues.isEmpty else { throw CaptionsError.emptyTrack }
        return cues
    }
}
